# Generated by Django 5.2.2 on 2025-06-07 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_token', models.CharField(max_length=512)),
                ('token_expiry', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('generated_script', models.TextField(blank=True, null=True)),
                ('audio_generated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exaggeration', models.FloatField(blank=True, null=True)),
                ('cfg_weight', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('seed_num', models.IntegerField(blank=True, null=True)),
                ('audio_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.user')),
            ],
        ),
    ]
