# Generated by Django 5.2.2 on 2025-06-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_user_updated_at_userinteraction_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='audio_file_path',
        ),
    ]
