# Generated by Django 5.2.2 on 2025-07-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_remove_userinteraction_created_at_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expiry',
        ),
    ]
